export type RootStackParamList = {
    Splash: undefined;
    Home: undefined;
    Main: undefined;
    'Lost and Found': undefined;
    'Adopt a pet': undefined;
    'Register Animal': undefined;
    'Confirm Adoption': undefined;
    'Adoption History': undefined;
    FoundandLostForm: undefined;
    PetDetailScreen: { petId: number }; 
    DonatedHistory: undefined;
    DonatedTransactionDetails: undefined;
    ResetPassword: undefined;
    AppTheme: undefined;
    UPISetting: undefined;
    AddUPISetting: undefined;
    VerifyUPISetting: undefined;
    NumberVerification: undefined;
    NumberVerificationWithNumber: undefined;
    NumberVerificationWithOTP: undefined;
    ForgotPasswordScreen: undefined;
    SystemSettings: undefined;
    Notifications: undefined;
    NoNotifications: undefined;
    NoChat: undefined;
    Login: undefined;
    Onboarding: undefined;
    ProfileSetupComplete: undefined;
  };
  